### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [KSposh/ksposh-zsh-theme#4]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by KSposh** [comment]
Hi there!

Thanks for showing interest.

I'll take a look into adding a license file in the coming days.

**Comment by KSposh** [comment]
@unixorn 

Just added the license file.
Feel free to use it at will.

Thanks again.
